services:
  mem0_store:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/mem0/storage
  openmemory-mcp:
    image: openmemory-mcp:9pve
    build: api/
    environment:
      - USER
      - API_KEY
    env_file:
      - api/.env
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    volumes:
      - ./api:/usr/src/openmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: openmemory-ui:9pve
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://mem0.9pve.com
      - NEXT_PUBLIC_USER_ID=root

volumes:
  qdrant_data:
